### ISSUE TITLE
YAML templates

### ISSUE THREAD

**Issue by mkolar** [4degrees/lucidity#20]
As much as I like using lucidity, using python as templates is a bit cumbersome to say the least. Have you though about implementing yaml instead (or json)? It would make template much easier to work with.

So instead of this:
```python
from lucidity import Template


def register():
    '''Register templates.'''
    episodeBase = 'Projects/{project.scode}_{project.name}/work'
    assetBase = 'Projects/{project.scode}_{project.name}/assets'
    renderBase = 'Projects/{project.scode}_{project.name}/renders'
    separator = '/'

    return [
        # Episodic SHOTS
        Template('ep-shot-publish', separator.join([episodeBase, '{episode}/{sequence}/{shot}/_Publish/'])),
        Template('ep-shot-work', separator.join([episodeBase, '{episode}/{sequence}/{shot}/{task}'])),
```
we would have this (or something similar of course):
```yaml
shot_paths:
    work_root: 'Projects/{project.scode}_{project.name}/work'
    render_root: 'Projects/{project.scode}_{project.name}/renders'
    
    ep-shot-publish: '@work_root/{episode}/{sequence}/{shot}/_Publish'
    ep-shot-work: '@shot_root/{episode}/{sequence}/{shot}/{task}'

```
